name: 11thHour
favicon: null
layout_spectrum: 0.22437706170603633
typography_spectrum: 0.5435583023354411
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#04619e'
    - '#eea83d'
    - '#de6034'
    - '#1a1a1a'
  brandStrength: 0.75
  lightness: 0.8689888000953943
  saturation: 0.9210754053201526
  rhythmicContrast: 0.0641743594314903
purpose: []
